name: Sync To Gitee

on: 
  push:
    branches:
      - master

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Sync to Gitee
              uses: wearerequired/git-mirror-action@master
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
              with:
                  source-repo: git@github.com:lulifa/RuiChen-AbpPro.git
                  destination-repo: git@gitee.com:lulifa/RuiChen-AbpPro.git

